--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- Name: db_fts; Type: DATABASE; Schema: -; Owner: postgres
--

\c postgres

DROP DATABASE IF EXISTS db_fts;

CREATE DATABASE db_fts WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'pt_BR.UTF-8' LC_CTYPE = 'pt_BR.UTF-8';


ALTER DATABASE db_fts OWNER TO postgres;

\connect db_fts

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: tb_post; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tb_post (
    id integer NOT NULL,
    title character varying(100),
    text_ text,
    tags character varying(200)
);


ALTER TABLE public.tb_post OWNER TO postgres;

--
-- Name: tb_post_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tb_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.tb_post_id_seq OWNER TO postgres;

--
-- Name: tb_post_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE tb_post_id_seq OWNED BY tb_post.id;


--
-- Name: id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY tb_post ALTER COLUMN id SET DEFAULT nextval('tb_post_id_seq'::regclass);


--
-- Data for Name: tb_post; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY tb_post (id, title, text_, tags) FROM stdin;
17	Red Hat Linux	Red Hat Linux é uma distribuição de Linux muito conhecida, líder do mercado nos Estados Unidos, criada e mantida pela Red Hat.\n\nUm grupo de programadores na Carolina do Norte decidiu tornar o Linux mais fácil para possibilitar às pessoas uma experiência mais tranquila com o mesmo. Como muitos grupos, seu objetivo era empacotar todos os bits necessários numa distribuição coerente, facilitando aos inexperientes o contato com o novo sistema operacional. No entanto. esta distribuição tinha uma característica distinta das demais. Em vez de ser uma cópia de um disco rígido que tivesse o Linux instalado, ou um conjunto de disquetes com partes diferentes do sistema operacional que podiam ser copiadas, esta distribuição foi baseada no conceito de pacotes.\n\nCada pacote fornece um pedaço diferente de software configurado, completamente testado e pronto para rodar. Se o usuário quiser instalar um novo programa, poderá carregar o pacote e instalá-lo, podendo imediatamente utilizá-lo. Se o usuário quiser remover algum programa, poderá removê-lo com um único comando. Este conceito ainda facilita as atualizações, uma vez que os pacotes são carregados de repositórios pré-configurados.\n\nO desenvolvimento do Linux no mundo é muito rápido[carece de fontes], provocando a geração de novas versões com frequência. Em outras distribuições, a actualização do software tornou-se complexa. Em uma atualização completa, normalmente o usuário teria que apagar tudo em seu disco rígido.\n\nDesde a introdução do Red Hat Linux em 1994, o Linux e o Red Hat tiveram um crescimento muito grande. O suporte para "hardwares" se tornou mais sofisticado, e o número de usuários e empresas que passaram a usar o Linux cresceu ao redor do mundo.[carece de fontes]\n\nO programa de instalação do Red Hat Linux pode ser executado em cerca de 15 minutos. Além dos pacotes de aplicativos (com a extensão RPM), há ainda um grande conjunto de ferramentas administrativas.\n\nA distribuição Red Hat está atualmente voltada para o mercado empresarial. No entanto, mantém a sua vertente comunitária através do projeto Fedora Core, que é uma distribuição totalmente livre, gratuita, desenvolvida comunitariamente e que serve de base ao Red Hat Enterprise Linux.	Linux Red Hat Unix
18	Fedora Linux	Fedora antigamente chamado Fedora Core é um sistema operativo que tem por base o Linux, a distribuição Linux é completamente livre de custos para poder usufruir e partilhar. Foi criada pela Red Hat. Atualmente mantida pelo Projeto Fedora (Fedora Project). Sua instalação é semelhante a versão 9 do Red Hat, em computadores com mais de 1 GHz de processamento e 256 de MB de memória RAM, a instalação padrão demora cerca de 30 minutos. Depois da instalação o GNOME fica como gestor de desktop padrão, podendo ser mudado para o KDE, WindowMaker, XFCE e etc. Já vem com o browser Mozilla Firefox, com LibreOffice e suporte a diversos idiomas, além de uma grande diversidade de programas para servidores e desktops. Novas versões do Fedora são lançadas aproximadamente a cada 6 meses, tendo como padrão três versões-teste para validação e correção de defeitos, reportados através do sistema bugzilla do projeto.	Linux Red Hat Software Livre Distribuição
19	Futebol	O futebol,[1] (do inglês association football ou simplesmente football) é um desporto de equipe jogado entre dois times de 11 jogadores cada um e um árbitro que se ocupa da correta aplicação das normas. É considerado o desporto mais popular do mundo, pois cerca de 270 milhões de pessoas participam das suas várias competições.[2] É jogado num campo retangular gramado, com uma baliza em cada lado do campo. O objetivo do jogo é deslocar uma bola através do campo para colocá-la dentro da baliza adversária, ação que se denomina golo (português europeu) ou gol (português brasileiro). A equipe que marca mais gols ao término da partida é a vencedora.[3]\n\nO jogo moderno foi criado na Inglaterra com a formação da Football Association, cujas regras de 1863 são a base do desporto na atualidade. O órgão regente do futebol é a Fédération Internationale de Football Association, mais conhecida pela sigla FIFA. A principal competição internacional de futebol é a Copa do Mundo FIFA, realizada a cada quatro anos. Este evento é o mais famoso e com maior quantidade de espectadores do mundo, o dobro da audiência dos Jogos Olímpicos.	esporte saúde jogo
1	Laranjeira	A laranja é o fruto produzido pela laranjeira (Citrus × sinensis), uma árvore da família Rutaceae. A laranja é um fruto híbrido, criado na antiguidade a partir do cruzamento da cimboa com a tangerina. O sabor da laranja varia do doce ao levemente ácido. Frequentemente, esta fruta é descascada e comida ao natural, ou espremida para obter sumo. As pevides (pequenos caroços duros) são habitualmente removidas, embora possam ser usadas em algumas receitas. A casca exterior pode ser usada também em diversos pratos culinários, como ornamento, ou mesmo para dar algum sabor. A camada branca entre a casca e as gomas, de dimensão variável, raramente é utilizada, apesar de ter um sabor levemente doce. É recomendada para "quebrar" o sabor ácido da laranja na boca, após terminar de consumir o fruto.\n\nA laranja doce foi trazida da China para a Europa no século XVI pelos portugueses. É por isso que as laranjas doces são denominadas "portuguesas" em vários países, especialmente nos Bálcãs (por exemplo, laranja em grego é portokali e portakal em turco), em romeno é portocala e portogallo com diferentes grafias nos vários dialectos italianos .	laranja fruta vitamina C
15	Ubuntu	Ubuntu é um sistema operacional (português brasileiro) ou sistema operativo (português europeu) de código aberto, construído a partir do núcleo Linux, baseado no Debian. É patrocinado pela Canonical Ltd (dirigida por Jane Silber).\n\nO Ubuntu diferencia-se do Debian por ser lançado semestralmente, por disponibilizar suporte técnico nos dezoito meses seguintes ao lançamento de cada versão (as versões LTS – Long Term Support – para desktop recebem 3 anos de suporte, e para servidor recebem 5 anos de suporte), e pela filosofia em torno de sua concepção. A proposta do Ubuntu é oferecer um sistema que qualquer pessoa possa utilizar sem dificuldades, independentemente de nacionalidade, nível de conhecimento ou limitações físicas. O sistema deve ser constituído principalmente por Software livre. Deve também ser isento de qualquer taxa.\n\nOs fãs do Ubuntu são conhecidos como "ubuntistas", "ubunteiros" ou "ubunteros". Atualmente, a página do Ubuntu no Distrowatch é segunda mais acessada (com base anual).[1]\n\nEm 8 de julho de 2005, Mark Shuttleworth e a Canonical Ltd anunciaram a criação da Fundação Ubuntu e providenciaram um suporte inicial de US$ 10 milhões. A finalidade da fundação é garantir apoio e desenvolvimento a todas as versões posteriores à 5.10.	sistema operacional linux software livre
20	Basquetebol	O basquetebol (basquete (português brasileiro) ou básquete (português europeu) ) ou bola ao cesto é um desporto colectivo inventado em 1891 pelo professor de Educação Física canadense James Naismith, na Associação Cristã de Moços de Springfield (Massachusetts), Estados Unidos.[1] É jogado por duas equipes de 5 jogadores, que têm por objetivo passar a bola por dentro de um cesto colocado nas extremidades da quadra, seja num ginásio ou ao ar livre.\n\nOs aros que formam os cestos são colocados a uma altura de 3 metros e 5 centímetros. Os jogadores podem caminhar no campo desde que driblem (batam a bola contra o chão) a cada passo dado. Também é possível executar um passe, ou seja, atirar a bola em direcção a um companheiro de equipe.[1]\n\nO basquetebol é um desporto olímpico desde os Jogos Olímpicos de Verão de 1936 em Berlim.\n\nO nome vem do inglês basketball, que significa literalmente "bola na cesta".[1] É um dos desportos mais populares do mundo.	basquete esporte saúde jogo
21	Voleibol	Voleibol (chamado frequentemente no Brasil de Vôlei e em Portugal de Vólei) é um desporto praticado numa quadra dividida em duas partes por uma rede, possuindo duas equipes de seis jogadores em cada lado. O objetivo da modalidade é fazer passar a bola sobre a rede de modo a que esta toque no chão dentro da quadra adversária, ao mesmo tempo que se evita que os adversários consigam fazer o mesmo. O voleibol é um desporto olímpico, regulado pela Fédération Internationale de Volleyball (FIVB).	vôlei esporte saúde jogo
22	Saúde	Quando a Organização Mundial da Saúde foi criada, pouco após o fim da Segunda Guerra Mundial, havia uma preocupação em traçar uma definição positiva de saúde, que incluiria fatores como alimentação, atividade física, acesso ao sistema de saúde e etc. O "bem-estar social" da definição veio de uma preocupação com a devastação causada pela guerra, assim como de um otimismo em relação à paz mundial — a Guerra Fria ainda não tinha começado. A OMS foi ainda a primeira organização internacional de saúde a considerar-se responsável pela saúde mental, e não apenas pela saúde do corpo.\n\nA definição adotada pela OMS tem sido alvo de inúmeras críticas desde então. Definir a saúde como um estado de completo bem-estar faz com que a saúde seja algo ideal, inatingível, e assim a definição não pode ser usada como meta pelos serviços de saúde. Alguns afirmam ainda que a definição teria possibilitado uma medicalização da existência humana, assim como abusos por parte do Estado a título de promoção de saúde.\n\nPor outro lado, a definição utópica de saúde é útil como um horizonte para os serviços de saúde por estimular a priorização das ações. A definição pouco restritiva dá liberdade necessária para ações em todos os níveis da organização social.\n\nChristopher Boorse definiu em 1977 a saúde como a simples ausência de doença; pretendia apresentar uma definição "naturalista". Em 1981, Leon Kass questionou que o bem-estar mental fosse parte do campo da saúde; sua definição de saúde foi: "o bem-funcionar de um organismo como um todo", ou ainda "uma actividade do organismo vivo de acordo com suas excelências específicas." Lennart Nordenfelt definiu em 2001 a saúde como um estado físico e mental em que é possível alcançar todas as metas vitais, dadas as circunstâncias.\n\nAs definições acima têm seus méritos, mas provavelmente a segunda definição mais citada também é da OMS, mais especificamente do Escritório Regional Europeu: A medida em que um indivíduo ou grupo é capaz, por um lado, de realizar aspirações e satisfazer necessidades e, por outro, de lidar com o meio ambiente. A saúde é, portanto, vista como um recurso para a vida diária, não o objetivo dela; abranger os recursos sociais e pessoais, bem como as capacidades físicas, é um conceito positivo.\n\nEssa visão funcional da saúde interessa muito aos profissionais de saúde pública, incluindo-se aí os médicos, enfermeiros, fisioterapeutas e os engenheiros sanitaristas, e de atenção primária à saúde, pois pode ser usada de forma a melhorar a eqüidade dos serviços de saúde e de saneamento básico, ou seja prover cuidados de acordo com as necessidades de cada indivíduo ou grupo.	vida OMS biologia
23	Ursídeos	Os ursídeos (latim científico: Ursidae) constituem uma família de mamíferos plantígrados, da ordem dos carnívoros, geralmente de grande porte, compreendendo os ursos e o panda. Embora classificado como urso, e logo após, como procionídeo, junto com o panda-vermelho, o panda-gigante foi recolocado dentro da família dos ursídeos devido às novas pesquisas genéticas. Algumas características comuns dos ursos são pelagem espessa, rabo curto, o olfato desenvolvido e as garras não retráteis. Os ursídeos são geralmente animais omnívoros.\n\nAs espécies mais antigas e primitivas desta família estão reunidas no Gênero Ballusia, do Mioceno Inferior, que ainda retêm características similares aos Hemicyonidae. Do Ballusia descende o gênero Ursavus, fonte dos Ursíneos, e talvez o Agriarctos, ancestral dos Agrioteríneos.\n\nOs ursos existem em todos os continentes, em exceção na África, embora algumas fontes afirmem terem avistado o Urso nandi, sem no entanto comprovarem a sua existência.	urso animal mamífero
24	Panda-gigante	O panda-gigante ou urso-panda (nome científico: Ailuropoda melanoleuca, do grego: ailuros, gato + poda, pés; e melano, preto + leukos, branco) é um mamífero herbívoro da família Ursidae endêmico da República Popular da China. O focinho curto lembrando um urso de pelúcia, a pelagem preta e branca característica e o jeito pacífico e bonachão o tornam um dos animais mais queridos pela humanidade. Extremamente dócil e tímido, dificilmente ataca o homem, a não ser quando extremamente irritado.	ursídeo animal herbívoro
2	Ananás	Ananás ou abacaxi é uma planta monocotiledônea da família das bromeliáceas, subfamília Bromelioideae. Os abacaxizeiros cultivados pertencem à espécie Ananas comosus, que compreende muitas variedades frutíferas. Há também várias espécies selvagens, pertencentes ao mesmo gênero e grupo. O fruto, quando maduro, tem o sabor bastante ácido e muitas vezes adocicado. Em culinária pode ser utilizado como um poderoso amaciante de carnes. Habitualmente usa-se a polpa da fruta, mas seu miolo e as cascas podem ser aferventadas para produção de sucos.	ananás abacaxi fruta
25	Limão	O limão (conhecido no Brasil e na Africa como limão siciliano ou limão verdadeiro; espécie Citrus x limon) é o fruto de uma pequena árvore de folha perene originária da região sudeste da Ásia. Apresenta diversas variedades cultivadas, sendo uma dezena delas frequentes, como por exemplo o limão Eureka [1], o limão Lisboa [2], o limão Fino, o limão Verno, o limão Villafranca,[3] o limão Lunário, etc.\n\nEste artigo não trata de três outras espécies de frutas cítricas, chamadas de limas em Portugal e de limões no Brasil, e mais conhecidas no Brasil do que o limão siciliano [4][5]: Citrus × latifolia ou limão-taiti[6][7], Citrus aurantiifolia ou limão-galego[7][8], Citrus x limonia ou limão-cravo.\n\nO limão siciliano for trazido da Pérsia pelos conquistadores árabes, disseminou-se na Europa[9]. Há relatos de limoeiros cultivados em Génova em meados do século XV bem como referências à sua existência nos Açores em 1494.\n\nSéculos mais tarde, em 1742, os limões foram utilizados pela marinha britânica para combater o escorbuto, mas apenas em 1928 se obteve a ciência sobre a substância que combatia tal doença, batizado ácido ascórbico ou vitamina C, na qual o limão proporciona em grande quantidade: o sumo do limão contém aproximadamente 500 miligramas de vitamina C e 50 gramas de ácido cítrico por litro. Atualmente é uma das frutas mais conhecidas e utilizadas no mundo.\n\nPopularizou-se no Brasil durante a chamada Gripe Espanhola (epidemia gripal de 1918)[10], quando atingiu preços elevados, chegando a ser comprada por de dez a vinte mil réis cada unidade.	fruta alimento cítrica
26	Husky siberiano	A husky siberiano[Nota] (em russo: Сибирский хаски) é uma raça canina oriunda da Rússia. Estes cães são conhecidos da Sibéria a quase 2 000 anos, quando foram especialmente desenvolvidos para puxar trenós em condições extremas pelos Chukchi. Em 1909, saídos da Sibéria rumo ao Alasca, começaram a se popularizar pelo mundo. Alguns anos mais tarde, ajudaram a salvar a população de uma aldeia na área americana, quando levaram medicamentos e suprimentos aos habitantes isolados por uma tempestade. Por este feito, um particular exemplar tornou-se muito famoso: Balto.[1]\n\nFisicamente é considerado um animal de trabalho rápido, de movimentos fluentes e corpo compacto, protegido por uma densa, porém não longa, pelagem. É ainda capaz de percorrer grandes distâncias a uma velocidade moderada. Classificados como fortes e resistentes, não possuem aparência rústica ou pesada. As cores de sua pelagem são bastante variadas, indo do branco puro ao preto e branco.	cão cachorro canino
32	Guitarra clássica / Violão	Guitarra clássica - (no Brasil conhecida como violão[1] e em Portugal como viola) é uma guitarra acústica com cordas de nylon ou aço, concebida inicialmente para a interpretação de peças de música erudita. O corpo é oco e chato, em forma de oito[2], e feito de várias madeiras diferentes. O braço possui trastes que a tornam um instrumento temperado. As versões mais comuns possuem seis cordas de nylon, mas há violões com outras configurações, como o violão de sete cordas e o violão baixo, com 4 cordas, afinadas uma oitava abaixo das 4 cordas mais graves do violão.	instrumento música cordas
33	Bateria (instrumento musical)	A bateria é um conjunto de tambores (de diversos tamanhos e timbres) e de pratos colocados de forma conveniente com a intenção de serem percurtidos por um único músico, denominado baterista, geralmente, com o auxílio de um par de baquetas, vassourinhas ou bilros, embora no caso de alguns executantes, possam também ser usadas as próprias mãos.	percussão prato bumbo
27	Pastor-alemão	A pastor-alemão (português brasileiro) ou lobo-da-alsácia (português europeu)[a][b] (em alemão: Deutscher Schäferhund) é uma raça canina proveniente da Alemanha. É considerada umas das mais numerosas e estudadas ao redor do mundo. Provável descendente de cães pastores do noroeste deste país europeu, teve seu primeiro exemplar registrado no século XX, pelo aposentado da cavalaria alemã Max von Stephanitz. Propagandeados como mensageiros, batedores e carregadores, serviram ao exército alemão na Primeira Guerra Mundial, chamando a atenção dos exércitos inimigos, que levaram alguns exemplares consigo ao fim da guerra. Popularizados nos Estados Unidos e Reino Unido, tornaram-se celebridades da tv e do cinema, figurando em produções como Rin-Tin-Tin.\n\nNa década de 1970, já visto como um dos caninos mais difundidos do mundo, começou a passar por cruzamentos levianos, que geraram animais problemáticos e mais propensos as doenças comuns da raça, como a mielopatia degenerativa e a displasia coxofemoral. Modernamente é visto como o cão policial e militar mais bem sucedido do mundo, já que dizem representar lealdade, agilidade, cautela e amizade. É ainda bem sucedido como animal de pastoreio, em provas de obediência, localização e agility, já que seu adestramento não representa dificuldade para donos inexperientes.[1]\n\nFisicamente, pode chegar aos 44 kg e medir 66 cm. Sua pelagem, de subpelo denso e duro, varia nas cores castanho de capa preta, preto, marta e branco. A pelagem branca, apesar de ser indesejável para os padrões norte-americano e inglês, por exemplo, não é tão incomum, e em 2002 foi reconhecida pela FCI como uma nova raça em virtude dos esforços de criadores suíços: pastor branco suíço.	cão cachorro canino
28	Esporte / Desporto	Desporto, desporte, esporte (português brasileiro) ou desporto (português europeu) é toda a forma de praticar atividade física que, através de participação ocasional ou organizada, visa equilibrar a saúde ou melhorar a aptidão física e proporcionar entretenimento aos participantes. Pode ser competitivo, onde o vencedor ou vencedores podem ser identificados por obtenção de um objectivo, e pode exigir um grau de habilidade, especialmente em níveis mais elevados. São centenas os tipos de desportos existentes, incluindo aqueles para um único participante, até aqueles com centenas de participantes simultâneos, em equipas ou individualmente. Algumas actividades não-físicas, como jogos de tabuleiro e jogos de cartas são muitas vezes referidos como desportos, mas um desporto é geralmente reconhecido como sendo baseada na actividade física.\n\nDesportos são normalmente geridos por um conjunto de regras ou costumes. Eventos físicos, tais como marcar golos ou cruzar uma linha em primeiro muitas vezes definem o resultado de um desporto. No entanto, o grau de habilidade e desempenho em alguns desportos, como Salto ornamental, Adestramento e Patinagem no gelo é julgado de acordo com critérios bem definidos. Isto, em contraste com outras actividades julgadas, como concursos de beleza e de musculação, onde a habilidade não tem que ser mostrada e os critérios não são tão bem definidos.\n\nOs registos são mantidos e actualizados para a maioria dos desportos nos níveis mais elevados, enquanto que as falhas e as realizações são amplamente divulgadas na imprensa desportiva.\n\nOs desportos são na maioria das vezes jogados apenas por diversão ou pelo simples facto das pessoas precisarem de exercício para se manterem em boas condições físicas. No entanto, o desporto e em especial o profissional é muito competitivo e uma importante fonte de rendimento económico e entretenimento.	saúde competição habilidade
29	Música	A música (do grego μουσική τέχνη - musiké téchne, a arte das musas)[1] é uma forma de arte que se constitui basicamente em combinar sons e silêncio seguindo uma pré-organização ao longo do tempo.[2]\n\nÉ considerada por diversos autores como uma prática cultural e humana. Atualmente não se conhece nenhuma civilização ou agrupamento que não possua manifestações musicais próprias. Embora nem sempre seja feita com esse objetivo, a música pode ser considerada como uma forma de arte, considerada por muitos como sua principal função.\n\nA criação, a performance, o significado e até mesmo a definição de música variam de acordo com a cultura e o contexto social. A música vai desde composições fortemente organizadas (e a sua recriação na performance), música improvisada até formas aleatórias. A musica pode ser dividida em gêneros e subgêneros, contudo as linhas divisórias e as relações entre géneros musicais são muitas vezes sutis, algumas vezes abertas à interpretação individual e ocasionalmente controversas. Dentro das "artes", a música pode ser classificada como uma arte de representação, uma arte sublime, uma arte de espetáculo.\n\nPara indivíduos de muitas culturas, a música está extremamente ligada à sua vida. A música expandiu-se ao longo dos anos, e atualmente se encontra em diversas utilidades não só como arte, mas também como a militar, educacional ou terapêutica (musicoterapia). Além disso, tem presença central em diversas atividades coletivas, como os rituais religiosos[3], festas e funerais.\n\nHá evidências de que a música é conhecida e praticada desde a pré-história. Provavelmente a observação dos sons da natureza tenha despertado no homem, através do sentido auditivo, a necessidade ou vontade de uma atividade que se baseasse na organização de sons. Embora nenhum critério científico permita estabelecer seu desenvolvimento de forma precisa, a história da música confunde-se, com a própria história do desenvolvimento da inteligência e da cultura humana.	harmonia ritmo melodia
30	Violino	O violino é um instrumento musical, classificado como instrumento de cordas friccionadas. É o menor e mais agudo dos instrumentos de sua família [1] (que ainda possui a viola, o violoncelo, correspondendo ao Soprano da voz humana). O contrabaixo é considerado um primo afastado do violino. Ao contrário do que se pensa, o contrabaixo não vem do violino, mas da viola da gamba. O violino possui quatro cordas[2], com afinação da mais aguda à mais grave: Mi5, Lá4, Ré4 e Sol3. O timbre do violino é agudo, brilhante e estridente, mas dependendo do encordamento utilizado, podem-se produzir timbres mais aveludados. O som geralmente é produzido pela acção de friccionar as cerdas de um arco de madeira sobre as cordas. Também pode ser executado beliscando ou dedilhando as cordas (pizzicato), pela fricção da parte de madeira do arco (col legno), ou mesmo por percussão com os dedos ou com a parte de trás do arco.\n\nAssim como outros instrumentos de cordas, os violinos também podem ser amplificados eletronicamente. A sua utilização mais comum é nos naipes de cordas das orquestras. O género mais comum é a música erudita. Existem no entanto diversos músicos que o utilizam na música folclórica, jazz, rock e outros géneros populares.\n\nNa orquestra, o líder do naipe de primeiros-violinos é chamado de spalla. Depois do maestro, ele é o comandante da orquestra. O spalla fica à esquerda do maestro, logo na primeira estante do naipe dos primeiros-violinos.\n\nEsticada na parte inferior do arco estão as cerdas, que são feitas de vários fios de crina de cavalo, ou de material sintético.\n\nA extensão do violino é do Sol 3 (mais grave e a última corda solta), ao Si 6 (3 notas antes da mais aguda que se pode ouvir).	instrumento corda agudo
31	Guitarra	O nome guitarra refere-se a uma série de instrumentos de cordas dedilhadas, que possuem geralmente de 6 a 12 cordas tensionadas ao longo do instrumento e possuem um corpo com formato aproximado de um 8 (embora também existam em diversos outros formatos), além de um braço, sobre o qual as cordas passam, permitindo ao executante controlar a altura da nota produzida. Existem versões acústicas, que possuem caixa de ressonância e elétricas, que podem ou não possuir caixa de ressonância (ver: guitarra semiacústica), mas utilizam captadores e amplificadores para aumentar a intensidade sonora do instrumento.[1]\n\nAs guitarras, bem como a maior parte dos instrumentos de cordas são construídas pelo luthier. O músico que a executa é chamado guitarrista.	música instrumento corda
34	Baixo	O baixo ou contrabaixo, também conhecido como baixo e viola baixo em Portugal, é um instrumento musical melódico, destinado especificamente a executar a parte grave de uma linha musical. Pode ser acústico ou elétrico.\n\nO nome baixo pode ser dado também a específicos modelos de clássicas, mas que possuem afinação um pouco mais grave que a clássica tradicional; esta baixo clássica é afinada uma quarta abaixo da tradicional, e não pertence a família dos baixos.	contrabaixo instrumento corda grave
3	Cão	O cão (Canis lupus familiaris[1]), no Brasil também chamado de cachorro, é um mamífero canídeo e talvez o mais antigo animal domesticado pelo ser humano. Teorias postulam que surgiu do lobo cinzento no continente asiático há mais de 100 000 anos. Ao longo dos séculos, através da domesticação, o ser humano realizou uma seleção artificial dos cães por suas aptidões, características físicas ou tipos de comportamentos. O resultado foi uma grande diversidade de raças caninas, as quais variam em pelagem e tamanho dentro de suas próprias raças, atualmente classificadas em diferentes grupos ou categorias. As designações vira-lata (no Brasil) ou rafeiro (em Portugal) são dadas aos cães sem raça definida ou mestiços descendentes.\n\nCom expectativa de vida que varia entre dez e vinte anos, o cão é um animal social que, na maioria das vezes, aceita o seu dono como o "chefe da matilha" e possui várias características que o tornam de grande utilidade para o homem. Possui excelente olfato e audição, é bom caçador e corredor vigoroso, relativamente dócil e leal, inteligente e com boa capacidade de aprendizagem. Deste modo, o cão pode ser adestrado para executar um grande número de tarefas úteis, como um cão de caça, de guarda ou pastor de rebanhos, por exemplo. Assim como o ser humano, também é vítima de doenças como o resfriado, a depressão e o mal de Alzheimer, bem como das características do envelhecimento, como problemas de visão e audição, artrite e mudanças de humor.	cão canino animal cachorro
12	Sustentabilidade	Sustentabilidade é a habilidade de sustentar ou suportar uma ou mais condições, exibida por algo ou alguém. É uma característica ou condição de um processo ou de um sistema que permite a sua permanência, em certo nível, por um determinado prazo.[1] Ultimamente este conceito, tornou-se um princípio, segundo o qual o uso dos recursos naturais para a satisfação de necessidades presentes não pode comprometer a satisfação das necessidades das gerações futuras,e que precisou da vinculação da sustentabilidade no longo prazo, um "longo prazo" de termo indefinido, em princípio.[2]\n\nSustentabilidade também pode ser definida como a capacidade do ser humano interagir com o mundo, preservando o meio ambiente para não comprometer os recursos naturais das gerações futuras. É um conceito que gerou dois programas nacionais no Brasil. O Conceito de Sustentabilidade é complexo, pois atende a um conjunto de variáveis interdependentes, mas podemos dizer que deve ter a capacidade de integrar as Questões Sociais, Energéticas, Econômicas e Ambientais.\n\nCom a finalidade de preservar o meio ambiente para não comprometer os recursos naturais das gerações futuras, foram criados dois programas nacionais: o Procel (eletricidade) e o Conpet.\n\n• Questão Social: Sem considerar a questão social, não há sustentabilidade. Em primeiro lugar é preciso respeitar o ser humano, para que este possa respeitar a natureza. E do ponto de vista do ser humano, ele próprio é a parte mais importante do meio ambiente.\n\n• Questão Energética: Sem considerar a questão energética, não há sustentabilidade. Sem energia a economia não se desenvolve. E se a economia não se desenvolve, as condições de vida das populações se deterioram.\n\n• Questão Ambiental: Sem considerar a questão ambiental, não há sustentabilidade. Com o meio ambiente degradado, o ser humano abrevia o seu tempo de vida; a economia não se desenvolve; o futuro fica insustentável.\n\nO princípio da sustentabilidade aplica-se a um único empreendimento, a uma pequena comunidade (a exemplo das ecovilas), até o planeta inteiro. Para que um empreendimento humano seja considerado sustentável, é preciso que seja:\n\n    ecologicamente correto\n    economicamente viável\n    socialmente justo\n    culturalmente diverso\n	ecologia economia meio ambiente eletricidade
4	Lobo	Lobo ou lobo cinzento (Canis lupus) é o maior membro selvagem da família canidae. É um sobrevivente da Era do Gelo originário durante o Pleistoceno Superior, cerca de 300 mil anos atrás.[2] O sequenciamento de DNA e estudos genéticos reafirmam que o lobo cinzento é ancestral do cão doméstico (Canis lupus familiaris), contudo alguns aspectos desta afirmação têm sido questionados recentemente.[3] Uma série de outras subespécies do lobo cinzento foram identificadas, embora o número real de subespécies ainda esteja em discussão. Os lobos cinzentos são tipicamente predadores ápice nos ecossistemas que ocupam. Embora não sejam tão adaptáveis à presença humana como geralmente ocorre com as demais espécies de canídeos,[3] os lobos se desenvolveram em diversos ambientes, como florestas temperadas, desertos, montanhas, tundras, taigas, campos e até mesmo em algumas áreas urbanas.[4] O lobo cinzento, o lobo-vermelho (Canis rufus) e o lobo-etíope (Canis simensis) são as únicas três espécies classificadas como lobos. Os demais lobos pertencem a subespécies.	canino animal lobo
13	Python	Python é uma linguagem de programação de alto nível[4], interpretada, imperativa, orientada a objetos, de tipagem dinâmica e forte. Foi lançada por Guido van Rossum em 1991.[1] Atualmente possui um modelo de desenvolvimento comunitário, aberto e gerenciado pela organização sem fins lucrativos Python Software Foundation. Apesar de várias partes da linguagem possuírem padrões e especificações formais, a linguagem como um todo não é formalmente especificada. O padrão de facto é a implementação CPython.\n\nA linguagem foi projetada com a filosofia de enfatizar a importância do esforço do programador sobre o esforço computacional. Prioriza a legibilidade do código sobre a velocidade ou expressividade. Combina uma sintaxe concisa e clara com os recursos poderosos de sua biblioteca padrão e por módulos e frameworks desenvolvidos por terceiros.\n\nO nome Python teve a sua origem no grupo humorístico britânico Monty Python,[5] criador do programa Monty Python's Flying Circus, embora muitas pessoas façam associação com o réptil do mesmo nome (em português, píton ou pitão).	software livre BSD linguagem programação Guido van Rossum
14	FreeBSD	O FreeBSD é um sistema operacional livre do tipo Unix descendente do BSD desenvolvido pela Universidade de Berkeley.\n\nEstá disponível para as plataformas Intel x86, DEC Alpha, Sparc, PowerPC e PC98 assim como para as arquiteturas baseadas em processadores de 64bits IA-64 e AMD64.\n\nConsiderado como robusto e estável, geralmente é utilizado em servidores, como de Internet ou Proxies, mas também pode ser utilizado como estação de trabalho.	sistema operacional software livre BSD Berkeley
5	Amazônia	A Amazônia (português brasileiro) ou Amazónia (português europeu) (também chamada de Floresta Amazônica, Selva Amazônica, Floresta Equatorial da Amazônia, Floresta Pluvial ou Hileia Amazônica) é uma floresta latifoliada úmida que cobre a maior parte da Bacia Amazônica da América do Sul. Esta bacia abrange sete milhões de quilômetros quadrados, dos quais cinco milhões e meio de quilômetros quadrados são cobertos pela floresta tropical. Esta região inclui territórios pertencentes a nove nações. A maioria das florestas está contida dentro do Brasil, com 60% da floresta, seguido pelo Peru com 13% e com pequenas quantidades na Colômbia, Venezuela, Equador, Bolívia, Guiana, Suriname e França (Guiana Francesa). Estados ou departamentos de quatro nações têm o nome de Amazonas por isso. A Amazônia representa mais da metade das florestas tropicais remanescentes no planeta e compreende a mais biodiversa de floresta tropical do mundo. É um dos seis grandes biomas brasileiros.\n\nNo Brasil, para efeitos de governo e economia, a Amazônia é delimitada por uma área chamada "Amazônia Legal" definida a partir da criação da Superintendência do Desenvolvimento da Amazônia (SUDAM), em 1966. É chamado também de Amazônia o bioma que, no Brasil, ocupa 49,29% do território e abrange três (Norte, Nordeste e Centro-Oeste) das cinco divisões regionais do país, sendo o maior bioma terrestre do país. Uma área de seis milhões de hectares no centro de sua bacia hidrográfica, incluindo o Parque Nacional do Jaú, foi considerada pela UNESCO, em 2000 (com extensão em 2003), Patrimônio da Humanidade.\n\nA Floresta Amazônica foi pré-selecionada em 2008 como candidata a uma das Novas 7 Maravilhas da Natureza pela Fundação Sete maravilhas do mundo moderno. Em fevereiro de 2009, a Amazônia foi classificada em primeiro lugar no Grupo E, a categoria para as florestas, parques nacionais e reservas naturais.	floresta selva américa brasil peru colombia venezuela equador bolivia guiana suriname frança sudam
11	Culinária	A culinária é a arte de cozinhar[1], ou seja, confeccionar alimentos e foi evoluindo ao longo da história dos povos para tornar-se parte da cultura de cada um. A culinária está invariavelmente associada à cozinha, pois este é o local ideal para cozinhar. Os métodos de culinária variam de região para região, não só os ingredientes, como também as técnicas culinárias e os próprios utensílios. Por exemplo, a cataplana é um recipiente para cozinhar alimentos típico do Algarve, equivalente à tajine de Marrocos. A alheira de Mirandela é um dos alimentos mais exclusivos da cozinha portuguesa, enquanto no Brasil, os pratos típicos incluem a feijoada brasileira e o churrasco. O cozinheiro principal é normalmente conhecido como chef, assim reconhecido pela sua boa cozinha e dotes culinários.\n\nA cozinha muitas vezes reflete outros aspectos da cultura, tais como a religião – a carne de vaca é tabu entre os hindus, enquanto a de porco é proibida entre os muçulmanos e judeus – ou determinadas posições políticas, como o vegetarianismo em que não são consumidos alimentos provenientes de animais ou oriundo de animais como leite e ovos para esse efeito.\n\nO desenvolvimento industrial teve igualmente um grande impacto na forma como as pessoas se alimentam. Por exemplo, a maior incidência de pessoas trabalharem longe de casa ou terem mais horas de trabalho levou ao surgimento da comida rápida; por outro lado, a consciência da segurança alimentar e da qualidade dos alimentos levou à criação de regras, por vezes na forma de leis, sobre a forma como os alimentos devem ser vendidos.\n\nUma disciplina associada à culinária é a gastronomia que se ocupa, não do modo como os alimentos são preparados, mas principalmente no refinamento da sua apresentação. Outras disciplinas relacionadas são a nutrição e a dietética, que estudam os alimentos do ponto de vista da saúde ou da medicina.	comida cozinha gastronomia
16	Linux	Linux é um termo popularmente utilizado para se referir a sistemas operativos (português europeu) ou sistemas operacionais (português brasileiro) que utilizem o núcleo Linux. O núcleo Linux foi desenvolvido pelo programador finlandês Linus Torvalds, inspirado no sistema Minix. O seu código fonte está disponível sob a licença GPL (versão 2) para que qualquer pessoa o possa utilizar, estudar, modificar e distribuir livremente de acordo com os termos da licença.\n\nInicialmente desenvolvido e utilizado por grupos de entusiastas em computadores pessoais, os sistemas operativos (português europeu) ou sistemas operacionais (português brasileiro) com núcleo Linux passaram a ter a colaboração de grandes empresas como IBM, Sun Microsystems, Hewlett-Packard (HP), Red Hat, Novell, Oracle, Google, Mandriva e Canonical.[1]\n\nApoiado por pacotes igualmente estáveis e cada vez mais versáteis de softwares livres para escritório (LibreOffice, por exemplo) ou de uso geral (projeto GNU) e por programas para micro e pequenas empresas que na maioria dos casos em nada ficam a dever aos seus concorrentes proprietários, e interfaces gráficas cada vez mais amigáveis como o KDE e o GNOME, o núcleo linux, conhecido por sua estabilidade e robustez, tem gradualmente caído no domínio popular, encontrando-se cada vez mais presente nos computadores de uso pessoal atuais. Há muito entretanto destaca-se como o núcleo preferido em servidores de grandes porte, encontrando-se quase sempre presente nos mainframes de grandes empresas comerciais [2] e até mesmo no computador mais rápido do mundo, o K computer, japonês (lista TOP500).	linux sistema operacional unix
\.


--
-- Name: tb_post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('tb_post_id_seq', 34, true);


--
-- Name: pk_post; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tb_post
    ADD CONSTRAINT pk_post PRIMARY KEY (id);


--
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

